// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AnnotationPanel: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/AnnotationPanel.vue')['default']
    BackButton: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/BackButton.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElInput: typeof import('element-plus/es')['ElInput']
    FileUploader: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/FileUploader.vue')['default']
    HelloWorld: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/HelloWorld.vue')['default']
    ICarbonCaretLeft: typeof import('~icons/carbon/caret-left')['default']
    ICarbonCaretRight: typeof import('~icons/carbon/caret-right')['default']
    ICodiconBell: typeof import('~icons/codicon/bell')['default']
    IFeChevronLeft: typeof import('~icons/fe/chevron-left')['default']
    IFeLayer: typeof import('~icons/fe/layer')['default']
    IMdiBell: typeof import('~icons/mdi/bell')['default']
    IMdiCheck: typeof import('~icons/mdi/check')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiGoogle: typeof import('~icons/mdi/google')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    IMdiTrash: typeof import('~icons/mdi/trash')['default']
    IMdiUser: typeof import('~icons/mdi/user')['default']
    LabelList: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/LabelList.vue')['default']
    LoginCard: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/LoginCard.vue')['default']
    LoginInput: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/LoginInput.vue')['default']
    MyButton: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/MyButton.vue')['default']
    MyInput: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/MyInput.vue')['default']
    MyModal: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/MyModal.vue')['default']
    MyStepper: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/MyStepper.vue')['default']
    NavigationTop: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/Navigation/Top.vue')['default']
    NewTemplateAddCard: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/NewTemplate/AddCard.vue')['default']
    NewTemplateBox: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/NewTemplate/Box.vue')['default']
    NewTemplateImageCarousel: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/NewTemplate/ImageCarousel.vue')['default']
    NewTemplateLabelList: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/NewTemplate/LabelList.vue')['default']
    NewTemplateModal: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/NewTemplate/Modal.vue')['default']
    NewTemplateMouseCross: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/NewTemplate/MouseCross.vue')['default']
    SelectionPanel: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/SelectionPanel.vue')['default']
    Sidebar: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/Sidebar/Index.vue')['default']
    TemplateCard: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/TemplateCard.vue')['default']
    TemplateMarkers: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/TemplateMarkers.vue')['default']
    TemplateOverlay: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/TemplateOverlay.vue')['default']
  }
}

export { }
