// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AnnotationPanel: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/AnnotationPanel.vue')['default']
    FileUploader: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/FileUploader.vue')['default']
    HelloWorld: typeof import('C:/Users/Administrator/Documents/Projects/Personal/annotorious-test/src/components/HelloWorld.vue')['default']
  }
}

export { }
